[package]
name = "server-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde = { version = "1", features = ["derive"] }

