[package]
name = "server-runner"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
config = "0.13.3"
reqwest = { version = "0.11.18", features = ["blocking", "native-tls-vendored"] }
serde = { version = "1", features = ["derive"] }

